// <auto-generated />
namespace SimpleSurvey.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class QuestionIsActiveMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuestionIsActiveMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202104222157077_QuestionIsActiveMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
